CREATE SCHEMA AUTHORIZATION database_user
CREATE TABLE Product (
	product_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
	product_name VARCHAR2(50) NOT NULL UNIQUE, 
	product_cost NUMBER NOT NULL,
	PRIMARY KEY (product_id)
)
CREATE TABLE Member (
	member_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
	membership_number VARCHAR2(50) NOT NULL UNIQUE,
	forename VARCHAR2(50) NOT NULL,
	surname VARCHAR2(50) NOT NULL,
	PRIMARY KEY (member_id)
)
CREATE TABLE MemberProduct (
	memberproduct_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
	next_payment_date DATE DEFAULT CURRENT_DATE NOT NULL,
	PRIMARY KEY (memberproduct_id),
	product_id NUMBER CONSTRAINT FK_product_id REFERENCES Product,
	member_id NUMBER CONSTRAINT FK_member_id REFERENCES Member
)
CREATE TABLE Payment (
	payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	payment_date DATE NOT NULL,
	payment_amount NUMBER NOT NULL,
	PRIMARY KEY (payment_id),
	memberproduct_id NUMBER CONSTRAINT FK_memberproduct_id REFERENCES MemberProduct
);